name: Model Upload with SSE-KMS

on:
  push:
    paths:
      - "models/**" # Trigger on any file changes in the 'models' directory

jobs:
  upload_model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Securely use the secret key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Securely use the secret key
          aws-region: ${{ secrets.AWS_REGION }} # Use the region stored in the secret

      - name: Find model files
        id: find_models
        run: |
          # Find all model files in the models directory
          MODEL_FILES=$(find models -type f)
          echo "Model files found: $MODEL_FILES"
          echo "::set-output name=model_files::$MODEL_FILES"

      - name: Upload Models to S3 with SSE-KMS
        run: |
          # Variables
          S3_BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}"  # Use the secret for the bucket name
          KMS_KEY_ID="${{ secrets.KMS_KEY_ID }}"  # Use the secret for the KMS key ID
          MODEL_FILES="${{ steps.find_models.outputs.model_files }}"  # List of model files

          # Loop over each model file
          for MODEL_FILE in $MODEL_FILES
          do
            echo "Uploading model file to S3 with SSE-KMS: $MODEL_FILE"

            # Upload the model file directly to S3 with server-side encryption using KMS
            aws s3 cp $MODEL_FILE s3://$S3_BUCKET_NAME/ --sse aws:kms --sse-kms-key-id $KMS_KEY_ID

            echo "Model file uploaded successfully: $MODEL_FILE"
          done
